baseURL = "http://localhost:1313"
title = "awtw-sa-jira 技術文件"
theme = "hugo-book"
defaultContentLanguage = "zh-tw"

[params]
  BookMenuFromFiles = true
  BookToC = true
  BookSearch = true

[markup.goldmark.renderer]
  unsafe = true

